name: Blog
description: Blogging about stuffs
meta_description: "My blog & thoughts"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: "/blog"
domain_name: "https://piyushkhemka.me"
google_analytics: "UA-79238615-2"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://piyushkhemka.me/blog"
author: "Piyush Khemka"

# Disqus config
disqus-shortname: "piyushkhemka"
